### PR TITLE
Update - Responsive Design

### PR DESCRIPTION
**Pull request by Bashamega**
Solves: #1
Photo:
image

### CODE REVIEW

**Comment by Arun0021** [comment]
You can add buttons under the Gamebox and the box should be visible properly

**Comment by Arun0021** [comment]
Also don't delete the old code just comment it

**Comment by Bashamega** [comment]
> Also don't delete the old code just comment it

Sorry, I will fix it now

**Comment by Bashamega** [comment]
> Also don't delete the old code just comment it

Done

**Review by Arun0021 — APPROVED** [review]

**Review by Arun0021 — APPROVED** [review]

**Review by Arun0021 — APPROVED** [review]

**Pull request merged**
